README.md, descarteslabs/addons.py, descarteslabs/auth/__init__.py, descarteslabs/tests/helpers.py, descarteslabs/tests/test_metadata.py, descarteslabs/tests/test_places.py, setup.py
=> Tests for Public

descarteslabs/scripts/descarteslabs
Also, ensuring token exists before retrieving fields from payload. Addresses #20
=> Adding user feedback to login script.

descarteslabs/services/raster.py, descarteslabs/tests/test_raster.py
=> Fix invalid transpose with single-band results

.travis.yml
travis command line tool also reformatted the yaml
=> Slack Notifications

descarteslabs/scripts/metadata, descarteslabs/scripts/places, descarteslabs/services/metadata.py, descarteslabs/services/raster.py, descarteslabs/tests/test_metadata.py, descarteslabs/tests/test_raster.py
shape -> place for kwargs that accept slugs
shape -> geom for kwargs that accept geojson strings/dictionaries
location -> place
shape -> cutline for raster api
=> Breaks API, renames shapes/places/locations/geoms.

descarteslabs/services/metadata.py
=> Sort results by acquired

.travis.yml, descarteslabs/services/metadata.py, descarteslabs/tests/test_metadata.py
Removing direct flag, adding sat_id, passing lists to service
=> Updating Metadata

descarteslabs/scripts/raster
=> Fix place argument for raster script

descarteslabs/auth/__init__.py, descarteslabs/exceptions.py, descarteslabs/services/metadata.py, descarteslabs/services/places.py, descarteslabs/services/raster.py, descarteslabs/services/service.py
Raising custom exceptions instead of generic runtime error. 
Subclassing requests.Session() to keep the code DRY.
=> Custom Exception Classes

descarteslabs/scripts/descarteslabs
Fixes issue when user logs in for the first time and sees an error about CLIENT_ID.
=> Need a new auth after logging in.

descarteslabs/services/metadata.py, descarteslabs/services/places.py, descarteslabs/services/raster.py
This will better facilitate testing the client against multiple versions of the service.
https://docs.travis-ci.com/user/triggering-builds/#Merge-mode%3A-deep_merge
=> Service URLs from ENV

.travis.yml
Tested with trigger API: https://travis-ci.org/descarteslabs/descarteslabs-python/jobs/230428294/config
=> Fix Travis Build Error

descarteslabs/tests/test_metadata.py
This will probably not require any further changes in this repo.
=> add test case for cloud fraction bug

README.md, descarteslabs/__init__.py, setup.py
* Update changelog in README.md
* Update version tags
=> Release v0.3.0

descarteslabs/scripts/parser/auth.py, descarteslabs/scripts/parser/raster.py
=> Command-line py3 compatibility fixes

descarteslabs/services/metadata.py
Updating metadata summary docs to a more well-defined request/response
=> Fixing doctest

docs/DLTiles.ipynb, docs/index.rst, docs/wildfire_assessment_demo.ipynb
=> added wildfire and dltiles notebook to docs

README.md, descarteslabs/__init__.py
Add changelog data and bump version
=> Release v0.3.3

descarteslabs/services/metadata.py, descarteslabs/services/places.py, descarteslabs/services/raster.py, descarteslabs/services/service.py
TCP/TLS connections are now being reused, so requests complete a lot faster (tests seem to run at least 2x faster)
=> Simplify service calls and reuse sessions

README.md, descarteslabs/__init__.py
* Metadata bands/products search/get, with descriptions
* Additional Placetypes
* Better error handling for timeouts
=> Release v0.4.1.

descarteslabs/services/raster.py
Kind of tough to describe in words, ultimately this will probably need some visual examples.
=> Attempt to document alpha band behaviour explicitly

README.md, descarteslabs/__init__.py
Update Changelog
Bump __version__ to 0.4.6
=> Release v0.4.6

descarteslabs/services/metadata.py
Extra kwargs for unreleased features.
=> allow passing extra kwargs to bands and products search

descarteslabs/auth/__init__.py, descarteslabs/tests/test_auth.py
Just so we can have this in one place instead of n different implementations.
=> Shared namespace helper for all services and extensions

descarteslabs/services/metadata.py, descarteslabs/tests/test_metadata.py
Support for iterating through more than 10,000 metadata results.
=> Scrolling support

docs/DLTiles.ipynb, docs/DLTiles.rst, docs/getting_started.ipynb, docs/getting_started.rst, docs/index.rst, docs/land_cover_demo.ipynb, docs/land_cover_demo.rst, docs/places.ipynb, docs/places.rst, docs/wildfire_assessment_demo.ipynb, docs/wildfire_assessment_demo.rst
GitOrigin-RevId: 7384503783d67b9024b82021ff71fb52a790ccf7
=> Remove notebooks and use rst

docs/api.rst
GitOrigin-RevId: abd7e67642a5378320c0e1808aaab61c5b2871e7
=> Docs Regression

.github/workflows/public-ci.yml, descarteslabs/scenes/tests/test_geocontext.py
- should have coverage on mac here, so let's enable it
=> enable ci tests on mac os
